#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

local enabled = uci:get('tunneldigger', '@broker[0]', 'auto_mtu_enabled')
if not enabled then
  uci:set('tunneldigger', '@broker[0]', 'auto_mtu_enabled','1')
  uci:save('tunneldigger')
  uci:commit('tunneldigger')

end

os.execute('/etc/init.d/automtu enable')
