#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

local enabled = uci:get('network', 'mesh_vpn', 'auto_mtu_enabled')
if not enabled then
  uci:set('network', 'mesh_vpn', 'auto_mtu_enabled','1')
  uci:save('network')
  uci:commit('network')

end

os.execute('/etc/init.d/automtu enable')
